name: pt_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - gnuradio=3.10.4.0
